$(document).ready(function(){
    $("#signup-form").validate({
        rules:{
            fname:{
                required:true,
                minlength:4
            },
            emailAdd:{
                required:true,
                email:true
            },
            subj:{
                required:true,
                minlength:4
            },
            msg:{
                required:true,
                minlength:10,
                maxlength:50
            }
        }
    })
})